env:
  commonjs: true
  es2021: true
  node: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
rules:
  semi: ["error", "always"]
  indent: ["error", 2]
  space-before-function-paren: ["error", "never"]
